name: Pull Request

on:
  pull_request:
    branches:
      - main
      - develop
  # Also run on pushes to PR branches to catch issues early
  push:
    branches-ignore:
      - main
      - develop

jobs:
  build-test:
    uses: ./.github/workflows/build-test.yml
    with:
      node-version: '20'
